name: "API Health Check"

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  healthcheck:
    # ubuntu 버전 지정
    runs-on: ubuntu-22.04
    steps:
      # 릴리즈 서버 헬스 체크 진행
      - name: Release API Health Check
        uses: jtalk/url-health-check-action@v3
        with:
          url: ${{ secrets.API_URL }}
          max-attempts: 3 # 시도 횟수
          retry-delay: 1s # 시도 간격
